language: go
sudo: false
go: 1.9.x

os:
- linux

install:
- go get github.com/kardianos/govendor
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

script:
- make vendor-sync
- make cover-ci
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=profile.cov
- make vet
- GOOS=windows go build

branches:
  only:
  - master

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
