language: go
sudo: false
go: 1.9.x

os:
- linux

install:
- go get github.com/kardianos/govendor
- go get github.com/mattn/goveralls

script:
- make vendor-sync
- make test
- make vet
- GOOS=windows go build
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=profile.cov
branches:
  only:
  - master

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
