language: go
sudo: false
go: 1.9.x

os:
- linux

install:
- go get github.com/kardianos/govendor

script:
- make vendor-sync
- make test
- make e2etest
- make vet
- GOOS=windows go build
branches:
  only:
  - master

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
